FROM public.ecr.aws/docker/library/httpd:2.4
#FROM public.ecr.aws/lts/apache2:2.4-20.04_beta
#FROM public.ecr.aws/lts/ubuntu:edge

#RUN apt-get update && \
#    apt-get -y install apache2 libapache2-mod-jk && \
#    cp -v /usr/lib/apache2/modules/mod_jk.so /usr/local/apache2/modules/mod_jk.so

# Install apache and write hello world message
RUN echo '<html><body><h2>Hello World!</h2></body></html>' > /usr/local/apache2/htdocs/index.html

# Configure apache
# RUN echo '. /etc/apache2/envvars' > /root/run_apache.sh && \
#     echo 'mkdir -p /var/run/apache2' >> /root/run_apache.sh && \
#     echo 'mkdir -p /var/lock/apache2' >> /root/run_apache.sh && \ 
#     echo '/usr/sbin/apache2 -D FOREGROUND' >> /root/run_apache.sh && \ 
#     chmod 755 /root/run_apache.sh

EXPOSE 80

# CMD /root/run_apache.sh
